services:
  node4:
    build: .
    container_name: node4
    environment:
      NODE_ID: "4"
      BASE_RANDOM_SEED: "42"
      MIN_DELAY: "30"
      MAX_DELAY: "90"
      LOG_DIRECTORY: "/data"
    ports:
      - "9004:8000"
    volumes:
      - node4-data:/data
      - ./topology.json:/app/topology.json:ro

  node5:
    build: .
    container_name: node5
    environment:
      NODE_ID: "5"
      BASE_RANDOM_SEED: "42"
      MIN_DELAY: "30"
      MAX_DELAY: "90"
      LOG_DIRECTORY: "/data"
    ports:
      - "9005:8000"
    volumes:
      - node5-data:/data
      - ./topology.json:/app/topology.json:ro

  node6:
    build: .
    container_name: node6
    environment:
      NODE_ID: "6"
      BASE_RANDOM_SEED: "42"
      MIN_DELAY: "30"
      MAX_DELAY: "90"
      LOG_DIRECTORY: "/data"
    ports:
      - "9006:8000"
    volumes:
      - node6-data:/data
      - ./topology.json:/app/topology.json:ro

volumes:
  node4-data:
  node5-data:
  node6-data:
